[SECO-2521] - Checkmarx REST APIs conversion
dowjones/reapsaw pull request #21
Opened 2020-03-02 12:10 UTC by aleksandr-koshedran

2020-03-04 12:51 UTC, pasiechnay requested changes

2020-03-04 12:51 UTC, pasiechnay commented on sast_controller/drivers/cx/Checkmarx.py
> +                "client_secret": '014DF517-39D1-4453-B7B3-9930C563627C'}
Is it a real secret?

2020-03-04 12:51 UTC, pasiechnay commented on sast_controller/drivers/cx/CxManager.py
> +    if check_prj_exists:
We can use method get_project_id_by_name to check if the project exists

2020-03-04 12:51 UTC, pasiechnay commented on sast_controller/converters/CheckmarxReport.py
>                              issue['Recommendations'] = jira_recommendations[query_id]
Please add validation if query_id present in jira_recommendations

2020-03-04 12:51 UTC, pasiechnay commented on sast_controller/converters/CheckmarxReport.py
>                              issue["Description"] = self.info_message.format(jira_desc[cwe], group, category,
Please add validation if cwe present in jira_desc

2020-03-04 12:51 UTC, pasiechnay commented on sast_controller/drivers/cx/Checkmarx.py
> +            with open('/tmp/sast_controller/drivers/cx/urls.json') as urls:
Please use TMP_FOLDER variable

2020-03-04 12:51 UTC, pasiechnay commented on sast_controller/drivers/cx/Checkmarx.py
> +            path = os.path.dirname(os.path.abspath(__file__))
Unused variable

2020-03-04 12:51 UTC, pasiechnay commented on sast_controller/drivers/cx/Checkmarx.py
> +        try:
Do we need this try?

2020-03-04 12:51 UTC, pasiechnay commented on sast_controller/drivers/cx/Checkmarx.py
> +            if name == project.lower():
This code duplicates methods get_project_id_by_name and check_project_by_name
Should variable name also be in lowercase?

2020-03-04 12:51 UTC, pasiechnay commented on sast_controller/drivers/cx/CxManager.py
> +            owning_team='d728ada5-5a56-442e-9562-0f506be3ecae',
Is it internal information?

2020-03-19 12:40 UTC, oleksii-dowjones commented on sast_controller/bin/config.py
> +    TEAM_NAME = os.environ.get('TEAM_NAME', None)
why do we need this?

2020-03-19 12:40 UTC, oleksii-dowjones commented on sast_controller/bin/scan.py
> -    if report and report.ScanResults:
why?
Do you think report.ScanResults can't be None?

2020-03-19 12:40 UTC, oleksii-dowjones commented on sast_controller/converters/CheckmarxReport.py
> +                            #    jira_recommendations[query_id] = utils.get_jira_recommendations(cx_client, query_id)
if utils.get_jira_recommendations call is not supported by new API, we don't need to have this code here at all.
Please remove jira_recommendations and jira_desc variables and this try except block as you do nothing inside it.
The same for description.

2020-03-19 12:40 UTC, oleksii-dowjones commented on sast_controller/bin/config.py
> +    TEAM_NAME = os.environ.get('TEAM_NAME', None)
How does it currently work without knowing this?

2020-03-19 12:40 UTC, oleksii-dowjones commented on sast_controller/drivers/cx/CxManager.py
> +        team_name =  cxClient.get_team_id_by_name(Config.TEAM_NAME)
We can probably use the team of the user that issues a scan as default value.
In this case TEAM_NAME will be optional parameter.

2020-03-19 12:40 UTC, oleksii-dowjones commented on sast_controller/drivers/cx/CxManager.py
> +        cxClient.logger.critical("Team not found")
should we just stop here?
Any reason to continue?

2020-03-19 12:40 UTC, oleksii-dowjones commented on sast_controller/drivers/cx/CxManager.py
> +        if scan_status == 'Failed':
If the scan fails, we have infinite loop.

2020-03-19 12:40 UTC, oleksii-dowjones commented on sast_controller/drivers/cx/CxManager.py
> +    while report_status != 'Created':
What are possible values for report status?
Can it be failed? In this case infinite loop again.
We should probably handle usual flow, for example, in progress and created statuses
and if status is not in created and in progress, exit with a log message.

2020-03-19 12:40 UTC, oleksii-dowjones commented on sast_controller/drivers/cx/CxManager.py
> +                                       preset_id=preset_id,
If the project already exists with some preset_id, can this call change it?
If yes, this isn't possibly expected behavior, because setting preset id from Checkmarx UI won't make any sense.

2020-03-19 12:40 UTC, oleksii-dowjones commented on sast_controller/drivers/cx/CxManager.py
> +import os
please reorder imports in alphabetical order

2020-03-19 12:44 UTC, oleksii-dowjones commented on sast_controller/drivers/cx/Checkmarx.py
> +		return False
This looks a bit unexpected. I expect project id here or, probably, None if it's not found.
But not False.

2020-03-19 12:44 UTC, oleksii-dowjones commented on sast_controller/drivers/cx/Checkmarx.py
> +		return False
the same

2020-03-20 10:46 UTC, oleksii-dowjones commented on sast_controller/drivers/cx/Checkmarx.py
> +                raise Exception("Keyword not exists")
does not exist

2020-03-20 10:46 UTC, oleksii-dowjones commented on sast_controller/drivers/cx/Checkmarx.py
> +        try:
have the same question

2020-03-20 10:56 UTC, oleksii-dowjones commented on sast_controller/drivers/cx/CxManager.py
> +    preset_id = 1
please check preset of newly created projects
it should be the same as in SOAP

2020-04-07 15:05 UTC, aleksandr-koshedran commented on sast_controller/drivers/cx/Checkmarx.py
> +                "client_secret": '014DF517-39D1-4453-B7B3-9930C563627C'}
no,  client_id  is a public 

https://checkmarx.atlassian.net/wiki/spaces/KC/pages/584024249/Using+the+Policy+Management+REST+API

2020-08-26 11:05 UTC, merged